### ISSUE TITLE
Error:  "FloatDomainError in Services#index"

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#98]
Platform:  Windows 10E
PB Branch:  DEV 

App launches from a console fine, but when trying to access the WebUI, I get this error:

```
FloatDomainError in Services#index
Showing C:/Sites/Plex-Board/app/views/plex_services/_now_playing.html.erb where line #11 raised:

NaN
Extracted source (around line #11):
9
10
11
12
13
14
              

  def get_percent_done
    ((self.progress.to_f / self.total_duration.to_f) * 100).to_i
  end

  def as_json(options)

Trace of template inclusion: app/views/services/index.html.erb

Rails.root: C:/Sites/Plex-Board

Application Trace | Framework Trace | Full Trace
app/models/plex_session.rb:11:in `to_i'
app/models/plex_session.rb:11:in `get_percent_done'
app/views/plex_services/_now_playing.html.erb:11:in `_app_views_plex_services__now_playing_html_erb__91625486_61311936'
app/views/services/index.html.erb:26:in `block (2 levels) in _app_views_services_index_html_erb___314001050_59050104'
app/views/services/index.html.erb:21:in `block in _app_views_services_index_html_erb___314001050_59050104'
app/views/services/index.html.erb:18:in `_app_views_services_index_html_erb___314001050_59050104'
Request

Parameters:

None
Toggle session dump
Toggle env dump
Response

Headers:

None

```

**Comment by scytherswings** [comment]
Fixed in dev by enforcing more strict values for PlexSessions and related objects.
